var TIPO_CONSTANTS = {
  COGNITO: {
	      REGION: '${env.COGNITO_REGION}',
	      IDENTITY_POOL_ID: '${env.COGNITO_IDENTITY_POOL_ID}',
	      USER_POOL_ID: '${env.COGNITO_USER_POOL_ID}',
	      CLIENT_ID: '${env.COGNITO_CLIENT_ID}'
  }
};